### ISSUE TITLE
okay

### ISSUE THREAD

**Issue by pmh-only** [gmstcl/elasticorn#1]
hmmm very nice README

isn't ya? 🤔

**Comment by xliohy** [comment]
Oh, hello. I'm a Klumm helper at Gongju Meister High School. I talked to you after task one. Do you remember

**Comment by pmh-only** [comment]
it's hard to remember but long time no see!

**Comment by xliohy** [comment]
Aha, they asked me what I scored after the first assignment. They asked me which school I went to and how many people came to the club. It's been a while for me, too
